spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carReservation
    username: me
    password: 2005
    driver-class-name: org.postgresql.Driver
    flyway:
      enabled: true
      locations: classpath:db.migration
